### ISSUE TITLE
🆔  TC 06 Registro: RFALLO- 04 - Redirección a la Activity Login en caso de registro exitoso.

### ISSUE THREAD

**Issue by PaulaVelezz** [Web-Developers2-0/ProyectoIntegradorMobile#178]
🆔 TC 06 Registro: RFALLO - 04
Referencia Plantilla Test Case: https://docs.google.com/spreadsheets/d/11SA8NfmLn1Otesp3XmV4BOo9hCQ05P8g/edit?gid=2074160715#gid=2074160715

📝 Descripción:
Se ha detectado que, al realizar un registro exitoso, con credenciales validas, no se redirige a la próxima pantalla, solo se muestra un mensaje de éxito.

❌ Resultado Actual:
No se hace la redirección automáticamente a la activity Login una vez se registra exitosamente.

✔️ Resultado Esperado:
Que se realice la redirección automáticamente a la pantalla Login, además de mostrar un mensaje de éxito.

📸 Capturas:
![Image](https://github.com/user-attachments/assets/d984157a-a665-4ddb-82ea-d628565249de)
![Image](https://github.com/user-attachments/assets/b1f408d9-d2a5-4861-a1a7-36337d980847)
![Image](https://github.com/user-attachments/assets/5d8539cd-b0c0-459b-ad07-d099ae97c5b1)

**Comment by 1pame** [comment]
- FALLO SOLUCIONADO -
