### ISSUE TITLE
#US21 #TK06 Los diseños deben ser entregados en formato editable y en alta resolución para revisión por parte del equipo de desarrollo.

### ISSUE THREAD

**Issue by 1pame** [Web-Developers2-0/ProyectoIntegradorMobile#78]

**Comment by emirobles** [comment]
Mockups: https://www.figma.com/design/hqPUf4Nwd2JQWRW7fNFqpy/Prototipo-App-Planet-Super-Heroes?node-id=0-1&node-type=CANVAS&t=XSapryM9x0UZHVr5-0

Prototipo:
https://www.figma.com/proto/hqPUf4Nwd2JQWRW7fNFqpy/Prototipo-App-Planet-Super-Heroes?node-id=1-2&node-type=FRAME&t=XSapryM9x0UZHVr5-0&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=1%3A2&show-proto-sidebar=1
